### ISSUE TITLE
Sound

### ISSUE THREAD

**Issue by BaronOsbourne** [evilgoldfish/LockGlyphX#44]
When I select the default sound it plays the Apple Pay sound instead.

**Comment by tomwat544** [comment]
That's because the default sound it themed. If the default sound for your theme is Apple Pay then that is what it will play.

**Comment by Sticktron** [comment]
The default sound IS the Apple Pay sound :)

**Comment by tomwat544** [comment]
Oh, ok thanks. BTW thanks for making g0blin! It awesome to have a jailbreak again!
